README.md

related: #10 
updated command in docs
run command in docs

docs: fixed docker run command for adding volume ~/.tokenlists

---

silverback/middlewares.py

refactor: display hex for message to avoid uncaught error

---

example.py
setup.py
silverback/application.py
silverback/runner.py
silverback/settings.py

feat: new block timeout set

---

setup.py
silverback/application.py
silverback/runner.py

fix: better local default for new block timeout [SBK-210]

---

Dockerfile

fix(docker): use stable base image (plus update for 3.10 base) [SBK-222]

---

CONTRIBUTING.md
README.md
example.py
setup.py
silverback/__init__.py
silverback/_cli.py
silverback/application.py
silverback/exceptions.py
silverback/runner.py

fixes: #19 
If we want the other way, will change everything to the other way
Also fixes repo links

refactor!: casings

---

.github/workflows/docs.yaml
setup.py

Some issues with docs CI, also added missing dependency per https://github.com/ApeWorX/silverback/pull/35#discussion_r1327676406

fix: docs ci [SBK-282]

---

silverback/application.py
silverback/exceptions.py
silverback/runner.py

Add more docstrings to our classes, so they show up in auto-generated documentation

docs: update automated docs [SBK-285]

---

README.md
docs/index.md
docs/userguides/development.md

Add userguide for developing a SIlverback application

docs: add development userguide [SBK-286]

---

.github/workflows/test.yaml
README.md
pyproject.toml
setup.py

chore: add Python 3.12 as supported

---

setup.py

chore: upgrade TaskIQ and dev deps

---

silverback/cluster/client.py
silverback/cluster/types.py

Small renaming update
~~- [x] New test cases have been added and are passing~~
~~- [x] Documentation has been updated~~

refactor: platform updated `organizations` to `workspaces`

---

README.md

docs: use permanent link to example in quickstart userguide

---

silverback/cluster/types.py
tests/test_cluster.py

refactor(cluster): update ClusterConfiguration for final release

---

silverback/cluster/types.py

fix(cluster): owner has wrong type `AddressType`

---

docs/index.rst

Remove unnecessary `ape_` prefix.
fixes: #

docs: remove ape prefix

---

docs/commands/cluster.rst

docs: update cli reference

---

silverback/_cli.py

fix(cli): bad display for `cluster info`

---

docs/userguides/managing.md
silverback/_cli.py

```
$ silverback cluster list testing2
- test (Deprovisioning)
- stream (Removed)
- stream2 (Running)
- update2 (Created)
- testing3 (Created)
```
fixes: #

feat: add cluster status to cluster list

---

silverback/_cli.py

Adds version flag to CLI
fixes: #144 
Copied ape code
Run `silverback --version`

feat(cli): add version to CLI

---

.pre-commit-config.yaml
docs/userguides/deploying.md
docs/userguides/development.md
setup.py
silverback/subscriptions.py
silverback/worker.py

Upgrade lint and pre-commit since things were failing in the tests.
fixes: #

chore: update lint

---

silverback/cluster/client.py

Fix adding new variables to cluster.
fixes: #

fix: new cluster vars

---

silverback/cluster/client.py

fix the delete method with name not id

fix: delete method

---

silverback/_cli.py
silverback/cluster/client.py
silverback/cluster/types.py

Update `silverback cluster bots` commands new, update, and list so that it connects with the cluster.
fixes: #

fix: cluster bots commands

---

silverback/cluster/types.py

fix: ClusterHealth model not following the input we are looking for

---

silverback/_cli.py
silverback/cluster/client.py

feat(cluster): add cluster migration command [Platform only]

---

silverback/_cli.py

Noticed that if a bot had a variable group that doesn't exist anymore, the CLI was raising. Also didn't protect against trying to update w/ unknown variable groups 

fix(cli): display warning/raise for unknown variable groups

---

silverback/_cli.py

fix(cli): forgot to fix display of update bot in #200

---

silverback/_cli.py

fix(cli): clear_environment had bad logic

---

silverback/_cli.py

refactor(cli): warn about hitting paid limit for bots

---

silverback/_cli.py

fix(cli): set environment logic on bot update

---

silverback/cluster/client.py

A change was made upstream, need this in SDK

fix(cluster): use PATCH not PUT for updating a Bot

---

silverback/cluster/types.py

Logging display was slightly off

refactor(cluster): fix log display

---

setup.py

ApePay 0.3.5 has a bug fix that should avoid a problem I was seeing downstream. It also just is a nice update to have

chore(deps): update pin of ApePay for bug fix

---

silverback/cluster/client.py

fix(cluster): increase timeout on some cluster commands

---

silverback/_cli.py

Note was kinda old, it doesn't seem to take too long anymore

fix(cli): reduce new cluster wait time suggestion

---

pyproject.toml
silverback/_cli.py
silverback/_click_ext.py

feat(cli): add ability to use globbed names for some commands

---

.gitignore
ape-config.yaml
setup.py
silverback/_build_utils.py
silverback/_cli.py

Noticed with ApePay (fixed: 6d30405) and also running the silverback example bot in the Platform (fixed: e7ae59a) that there was some bugs, so cleaned up some of the build process and added some improvements, as well as made sure that the build output is more helpful while it's running
fixes: #132
`silverback build --generate`

fix(build): copy config and contracts folder over

---

setup.py

Updates ape to fix an annoying issue that was plaguing my bots

chore: update Ape to latest version (pulls in fix for stable)

---

silverback/main.py

The fix in #223 forgot to await on async system tasks (only some of them), so refactor how that inner task function works

fix: forgot to await system task wrapper

---

setup.py
silverback/exceptions.py
silverback/main.py
silverback/runner.py

Found several bugs with TaskIQ and deserialization that were causing issues

fix(Runner): taskiq issues

---

bots/example.py
docs/userguides/development.md
setup.py
silverback/main.py
silverback/runner.py
silverback/types.py

feat: add cron tasks

---

bots/example.py
docs/userguides/development.md
silverback/main.py
silverback/runner.py

Adds support for filter kwargs on event log handlers
fixes: https://github.com/ApeWorX/silverback/issues/54
fixes: SBK-417
requires: #231

feat: event arg filtering

---

.github/workflows/test.yaml
docs/commands/cluster.rst
docs/userguides/managing.md
setup.py
silverback/_cli.py
silverback/_click_ext.py
silverback/cluster/mcp.py

This PR adds support for calling Cluster client API through Anthropic's Model Context Protocol
You have to run it via `silverback cluster mcp`

feat(cluster): add MCP server to work with Platform

---

silverback/_cli.py

feat(CLI): allow specifying environment variables by name only

---

silverback/recorder.py
silverback/runner.py
silverback/types.py

Added a small display showing when metrics are collected by executing a task. Makes it easier to debug using metrics
fixes: #53
~~- [ ] Documentation has been updated~~ (see #241)

feat(Runner): display metrics in logs

---

silverback/_build_utils.py

fix(build): use pyproject.toml, if exists

---

setup.py
silverback/_cli.py
silverback/_click_ext.py
silverback/cluster/auth.py
silverback/cluster/utils.py

Can't release a package using a branch pinned installation of a package, so... just removed the package (it's archived anyways)
Logged into both current and next auth

fix(Cluster): remove Fief client

---

silverback/cluster/auth.py
silverback/cluster/settings.py

refactor(Cluster): update auth to display errors better

---

silverback/exceptions.py
silverback/main.py

The exception wouldn't show the message because it was incorrectly used

fix: improper use of exception, created a new one

---

silverback/_cli.py
silverback/cluster/client.py
silverback/cluster/types.py
silverback/utils.py

Noticed it was a little difficult to display the info on how to pay, if needed. So added a subcommand for it.
Also fixes a UX issue when using the wrong chain to add time/cancel an existing stream

feat(CLI): add `cluster pay info` subcommand
