ApeWorX/silverback

- silverback/_cli.py
adds ape-cli-context in order to let debug verbosity be used
fixes: #6 
added ape_cli_context to click command
try running with -v DEBUG
> fix: ape cli context to add -v debug

- setup.py
- silverback/_cli.py
- tests/conftest.py
- tests/test_cli.py
Requires the release of Ape with this PR: https://github.com/ApeWorX/ape/pull/1486
> fix: verbosity fixes in CLI

- Dockerfile
Clean up the dockerfile, and build from builder with wheels
fixes: issue where the silverback docker image does not have the newest version of silverback
cleaned up the dockerfile using the techniques used in ape core
build the dockerfile
> fix: clean up dockerfile

- silverback/middlewares.py
- silverback/runner.py
Right now the exception just always says `Exception` and if there is not much of a message, such as unknown ecosystem, then it is really confusing. Also confused why `ethereum` is an unknown ecosystem but that is another story
It used to say:
```
ERROR: 0xb5ED1eF2a90527b402Cd7e7d415027CB94E1Db4E/event/StreamCreated - Exception: ethereum
```
Now it looks like:
```
ERROR: 0xb5ED1eF2a90527b402Cd7e7d415027CB94E1Db4E/event/StreamCreated - UnknownEcosystem: ethereum
```
> feat: include exception type in log message

- example.py
- silverback/application.py
- silverback/runner.py
- silverback/settings.py
Allow setting `start_block` everywhere, same as we did for new block timeout.
> feat: start block setting

- silverback/_cli.py
Fixes issue where the `SILVERBACK_NETWORK_CHOICE` envvar did not take precedence
> fix: make sure that envvars can override the default network option [SBK-223]

- setup.py
- silverback/__init__.py
- silverback/_cli.py
- silverback/exceptions.py
- silverback/runner.py
- silverback/subscriptions.py
Add support for using a websocket-based subscriptions for the polling algorithm
NOTE: Breaking change is renaming `LiveRunner` to to `PollingRunner` and removing it from export. `silverback run` will continue using the polling runner out of the box, however
Added `Web3SubscriptionManager` which allows multiple subscriptions to a Web3 RPC that supports `eth_subscribe`
NOTE: To use it, run your `silverback run` command with the `--runner silverback.runner:WebsocketRunner` flag
I tried it with the example, seems to run okay. Needs more validation probably.
> feat!: websocket runner [SBK-244]

- README.md
- silverback/application.py
Fixes a link in the README, docstrings, and trivial var name misspellings. 
With my text editor.
Look at it and click on it
> fix(docs): fix link to development guide

- silverback/application.py
The func sig changed in `ProviderContextManager.__exit__()` requiring the expected arguments.  This fixes the `atexit.register()` call to include the required args expected by `object.__exit__()`.
Change introduced in Ape framework in PR https://github.com/ApeWorX/ape/pull/1733
`None`
> fix: include args for __exit__ func sig [SBK-371]

- silverback/middlewares.py
- silverback/types.py
Fixes a minor discrepancy between handler_id and task_id.  This caused log_index and block number to not be set.
> fix: task ID and persistence discrepancy

- silverback/settings.py
Fixed an edge case where `self.network_manager.network.choice` on the `ManagerAccessMixin` isn't a valid network choice for `parse_network_choice()`.  
Ref: https://github.com/ApeWorX/ape/issues/1762
Added a bit of a workaround here since the adhoc network will have already been configured by a network bound command.
Run Silverback programmatically via a `NetworkBoundCommand`
> fix: add workaround for adhoc networks

- .mdformat.toml
- .pre-commit-config.yaml
- README.md
- example.py
- setup.py
- silverback/_cli.py
- silverback/application.py
- silverback/middlewares.py
- silverback/settings.py
> feat!: Handle 0.7 breaking changes and updates [SBK-369]

- silverback/middlewares.py
- silverback/utils.py
Made the message encoding/decoding in middleware recurisve, lest any mildly complex messages with bytes in them break the whole thing.
> fix: encode/decode bytes/HexBytes recursively in messages

- silverback/settings.py
Prevents an empty string from being given to a broker class if `SILVERBACK_BROKER_URI` is not defined.
> fix: if BROKER_URI is not defined, give the constructor None

- .github/workflows/docs.yaml
This will (probably) fix [the issue updating the repo seen in this job run](https://github.com/ApeWorX/silverback/actions/runs/8454906985/job/23161106159).
Grants write perms to the job.
> fix(devops): grant write perms to docs job in workflow

- .github/workflows/draft.yaml
And [another one](https://github.com/ApeWorX/silverback/actions/runs/8458155621/job/23171743638).
> fix(devops): adds write perms to drafter workflow

- silverback/runner.py
- silverback/subscriptions.py
Noticed when you shutdown unexpectedly, there's a lot of issues in the trace about not properly handling async tasks
some try..catch statements
run and app and randomly press `ctrl+C`
> fix: catch more shutdown issues to resolve shutdown without dropping

- setup.py
- silverback/application.py
- silverback/exceptions.py
- silverback/middlewares.py
- silverback/runner.py
- silverback/types.py
Refactor to dynamic registration of tasks, saving tasks (and their handlers) in a separate collection that can be accessed via an enum type to specify their class
Relates to https://github.com/ApeWorX/silverback/issues/57, as it migrates to a dynamic registration method via TaskIQ
Also should allow https://github.com/ApeWorX/silverback/pull/55#issuecomment-1977168440 to use dynamic registration to resolve the bug with multiple handlers with different filters not fully registering
New TaskIQ dynamic broker registration API
Everything should work as it did before, don't think this is breaking but wanted to call attention to commits to make sure they were reviewed fully for breaking behaviors
> refactor: allow multiple handlers

- .github/workflows/test.yaml
Pinned runner to macos-12 until setup-python is fixed.
Ref: https://github.com/ApeWorX/ape/pull/2020
> fix(devops): do not use macos-latest until there's a setup-python fix

- setup.py
- silverback/application.py
- silverback/middlewares.py
Fixes a label issue I ran across during testing.  Also added a couple of labels useful for distributed runner/worker.
> fix: label issues

- Dockerfile
Updates the `Dockerfile` python version to 3.11 because features.
Depends on: https://github.com/ApeWorX/ape/pull/2042
> chore: update docker container to python 3.11

- silverback/middlewares.py
- silverback/recorder.py
- silverback/runner.py
- silverback/settings.py
- silverback/types.py
I made a naming change that more accurately follows our intended platform naming for this subsystem
find/replace
Should be no change in functionality other than the environment variable you need to use to set it up
> refactor!: rename Persistence to Recorder

- .github/workflows/prtitle.yaml
- .github/workflows/test.yaml
- README.md
- docs/conf.py
- example.py
- pyproject.toml
- setup.py
- silverback/application.py
- silverback/recorder.py
- silverback/runner.py
- silverback/settings.py
- silverback/subscriptions.py
- silverback/types.py
It's getting pretty annoying to deal with Python 3.8's missing types, so I just want to drop it in our next breaking release
> refactor!: drop Python 3.8 & 3.9

- .gitignore
- example.py
- silverback/__init__.py
- silverback/_cli.py
- silverback/application.py
- silverback/exceptions.py
- silverback/middlewares.py
- silverback/recorder.py
- silverback/runner.py
- silverback/settings.py
- silverback/state.py
- silverback/types.py
Refactors the structure of `HandlerResult` to add support for serialized data structures for metrics
Makes a breaking change deprecating `SQLiteRecorder` in favor of `JSONLineRecorder`
Makes a breaking change to annotated Worker state and App state
Makes a larger refactor of `BaseRunner.run` startup sequence to reduce errant errors and give better logging
Adds a callback to allow configuring a recorder in `silverback run` command, and pipes that to `BaseRunner`
related: #59 
~~requires: #63, #66 (for proper labeling of results)~~
> feat!: add data acquisition to recorders

- silverback/recorder.py
- silverback/types.py
- tests/test_types.py
Fixes the error:
```
[...snip...]
File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/silverback/recorder.py", line 91, in from_taskiq
metrics=cls._extract_custom_metrics(result.return_value, task_name),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/mike/.venvs/silverback-cluster/lib/python3.11/site-packages/silverback/recorder.py", line 45, in _extract_custom_metrics
elif isinstance(result, ScalarType):  # type: ignore[arg-type,misc]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/typing.py", line 1689, in __instancecheck__
return self.__subclasscheck__(type(obj))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/typing.py", line 1693, in __subclasscheck__
if issubclass(cls, arg):
^^^^^^^^^^^^^^^^^^^^
File …
```
> fix: error checking type for "subscripted generics"

- setup.py
- silverback/application.py
- silverback/exceptions.py
- silverback/middlewares.py
- silverback/runner.py
- silverback/settings.py
- silverback/types.py
- silverback/utils.py
This PR adds the concept of "system tasks" which will be a set of internal tasks that Runners can run to obtain metadata from a worker about the types of tasks it supports, the task data required to construct a message, and other information that is needed for the platform to reduce repetitive state communication and storage about bots
fixes: https://github.com/ApeWorX/silverback/issues/57
New tasks were added using the `system:` pre-pend to their task names in order to prevent conflicts with user-defined tasks (as they cannot contain a colon)
[cce2798](https://github.com/ApeWorX/silverback/pull/82/commits/cce27982f906f4fa81dcce84098af80c02f0dc04) adds the "system configuration task" which will return the SDK version of the worker and also the set of task types it supports. This will be …
> feat!: stateless runner

- silverback/application.py
- silverback/types.py
Adds `TaskType.SYSTEM_USER_ALL_TASKDATA` to fetch all user defined tasks in one job.
> feat: adds task type SYSTEM_USER_ALL_TASKDATA

- docs/userguides/development.md
- silverback/settings.py
Adds the `SILVERBACK_BROKER_KWARGS` for config to allow dynamic configuration of the broker.  
Change should be non-breaking, but we probably want to remove `BROKER_URI` in a future breaking release.
fixes: #85
> feat: adds SILVERBACK_BROKER_KWARGS for broker config

- docs/userguides/development.md
- silverback/_cli.py
With talking to @Ninjagod1251 realized we are in a position now (thanks to https://github.com/ApeWorX/ape/pull/1623) where we can just auto-select which runner to run with
Unsure if we want to maintain backwards compatibility by allowing an override, but I can do that if needed
> refactor: auto-select runner

- .github/workflows/test.yaml
- README.md
- docs/userguides/development.md
I added detailed instructions for starting up the docker environment. Without better details, a new user would be stuck trying to get their environment to work.
I also removed the need for running the tests if there are no changes to the silverback, tests, pyproject.toml and the setup.py
Worked through the current instructions, repeatedly failed to get the docker environment up, had to be pointed in a couple of places to get everything ready to run. I documented the steps here.
Go to the `Full Environment Execution Example` section in the `README.md`, and follow the new instructions. Make sure the docker container runs without terming.
> fix: add more detailed instructions to README

- silverback/subscriptions.py
Adds `Web3SubscriptionsManager.get_subscription_data_nowait()` to add the ability to poll without a hanging iterator.
> feat: adds Web3SubscriptionsManager.get_subscription_data_nowait()

- silverback/settings.py
Adds `RESULT_BACKEND_KWARGS` to settings to allow more dynamic configuration of the result backend.
> feat: adds RESULT_BACKEND_KWARGS to settings

- silverback/settings.py
Fixed a bad type on settings from PR #96
> fix: wrong type on RESULT_BACKEND_KWARGS

- silverback/types.py
Handles deserialization of TaskResult.
fixes: #107
`ScalarDatapoint` may be in dict form.
```python
>>> from silverback.types import Datapoints
>>> from taskiq import TaskiqResult
>>> from silverback.recorder import TaskResult
>>> from silverback_cluster_common.types import InstancedTaskResult
>>> result = TaskResult.from_taskiq(TaskiqResult(is_err=False, log=None, return_value={'foo': 123, 'value': 0.01}, execution_time=0.39, labels={}, error=None))
>>> TaskResult.model_validate(result.model_dump())
TaskResult(task_name='handle_transfer', execution_time=0.39, error=None, completed=datetime.datetime(2024, 8, 9, 3, 26, 39, 738962, tzinfo=TzInfo(UTC)), block_number=6464337, metrics=Datapoints(root={'foo': ScalarDatapoint(type='scalar', data=123), 'value': ScalarDatapoint(type='scalar', …
```
> fix: handle deserialization of TaskResult

- docs/userguides/development.md
- silverback/settings.py
This PR add a small UX enhancement where `acct.set_autosign(True)` is automatically called if a `KeyfileAccount` is provided for the alias. This will assist testing in local scenarios for rapid prototyping with a local wallet.
fixes: #90 
```sh
$ silverback run example:app --network ethereum:mainnet
...  # runs just fine without a signer
$ silverback run example:app --network ethereum:mainnet --account <my-keyfile-alias>
INFO: Loading Silverback App with settings:
APP_NAME="bot"
...
Enter passphrase to permanently unlock 'my-keyfile-alias':
WARNING: Danger! This account will now sign any transaction it's given.
SUCCESS: Loaded Silverback App:
NETWORK="ethereum:mainnet"
SIGNER=<KeyfileAccount address=0x...  alias=dev >
INFO: Using WebsocketRunner: max_exceptions=3
...
```
~~- [ ] New test …
> feat: unlock acct for auto-signing if alias resolves to KeyfileAccount

- tests/test_types.py
fixes: #113 
The max int for Int96 is defined as `2**95 - 1` but the test was using `2**96 - 1`
> test: max type was off in the test

- silverback/subscriptions.py
Trivial change.  Just changed the log level for a Websocket receive timeout to a warning.
> chore: make sure websocket timeouts are logged as warnings

- silverback/runner.py
> fix: warn the user (instead of DEBUG) log when runtime exit

- .github/workflows/build.yaml
- Dockerfile
- README.md
- docs/userguides/development.md
- docs/userguides/platform.md
- silverback/_cli.py
- silverback/_click_ext.py
In an attempt to make the dev ux simpler, I allow for the path to be an option. If the path does not exist, we set the bath to `pathlib.Path.cwd()/bots/bot.py`
We check and raise if the file and/or the directory does not exist.
We are also adding a `Dockerfile` generator to the `_cli.py` file that will search the `bots/` directory for filenames. Each filename will be generated as a `Dockerfile.<filename>`. The Dockerfile will copy the filename into the `bots/` directory as `bot.py`.
fixes: #122 
fixes: #123 
fixes: SBK-564
fixes: SBK-563
Made minor changes to the `run` command and adding a method to generate the dockerfiles.
Without a `bots/` directory in the root of the project run:
```
silverback run --network ethereum:mainnet
```
This will raise and show a:
```
FileNotFoundError: The …
```
> feat(cli)!: find bots by default paths

- docs/userguides/platform.md
- setup.py
- silverback/_cli.py
- silverback/_click_ext.py
- silverback/cluster/client.py
- silverback/cluster/types.py
In anticipation for our beta launch, we give people the ability to fund their Clusters using the Silverback CLI
This PR adds support for funding newly created Clusters, adding more funds to extend the time of those Clusters, and also cancelling those Clusters via CLI
> feat(platform): add payment cli for streaming payments w/ ApePay

- Dockerfile
- README.md
- docs/userguides/development.md
- docs/userguides/platform.md
- example.py
- silverback/__init__.py
- silverback/_cli.py
- silverback/application.py
- silverback/exceptions.py
- silverback/main.py
- silverback/middlewares.py
- silverback/runner.py
- silverback/settings.py
- silverback/state.py
- silverback/types.py
This PR adds worker shared state (accessible via `app.state`) and adds 2 new system tasks to support loading and storing a snapshot of that managed state. Currently this is just `last_block_processed` and `last_block_seen`.
This paves the way for the `Parameter` feature, but does not include that just yet.
BREAKING CHANGE: state snapshot features migrates from runner to worker and must be triggered by runner
> feat!: add `app.state`

- silverback/cluster/client.py
```sh
$ silverback cluster bots new -g <some vargroup> ...
...                                                                                                                              
File "site-packages/silverback/_cli.py", line 859, in new_bot                                                      
environment = [cluster.variable_groups[vg_name].get_revision("latest") for vg_name in vargroups]                                                                              
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                        
File "site-packages/silverback/cluster/client.py", line 118, in get_revision                                       
handle_error_with_response(response) …
```
> fix(cluster): vargroup "latest" doesn't work

- silverback/_cli.py
If there are already plugins installed, the install command fails unless you call to update
fixes: #
> fix: auto run update

- silverback/cluster/client.py
Fixes the cluster & Workspace create/update must use Form encoded data, not JSON body (use data= instead of json=)
fixes: #137 
Tested creating clusters with cli and it works.
> fix: cluster and workspace form data

- silverback/_cli.py
- silverback/cluster/types.py
Change tier names from "Personal" and "Professional" to "Standard" and "Premium" and add payment amount when creating a streaming payment for a cluster
fixes: #140
> fix: payment cli

- silverback/_cli.py
- silverback/cluster/client.py
- silverback/cluster/types.py
Updates the `silverback cluster bots logs ...` command to support new logs interface.
> feat: updates bot logs command to support new interface

- silverback/_cli.py
- silverback/cluster/client.py
Fix `workspaces update` subcommand so that values could be `None` and original values would not be overwritten.
fixes: #
> fix: update workspaces

- silverback/_build_utils.py
- silverback/_cli.py
Added a check for `requirements.txt` and `ape-config.yaml` so `silverback build` doesn't fail if those files don't exist
fixes: #150 
Removed the lines pertaining to the `requirements.txt` and `ape-config.yaml` files and move them into a conditional within the build command.
```
python3 -m venv venv
pip install <this pr>
cd /to/a/silverback/directory/project
sivlerback build --generate
```
Check your dockerfile output in .silverback-images
```
mv requirements.txt req.txt
or if that file didn't exist
touch requirements.txt
silverback build --generate
```
Check your dockerfile output in .silverback-images and the requirements.txt lines should no longer be there.
> fix: silverback build missing files during generate

- silverback/_cli.py
- silverback/cluster/client.py
Add cli command for updating cluster name and slug.
fixes: #
> feat: add cluster update

- silverback/cluster/client.py
- silverback/exceptions.py
Http failure in client code should catch and re-raise those issues as `click.UsageError` exceptions instead of `RuntimeError`
fixes: #
> fix: raise UsageError

- silverback/_cli.py
- silverback/cluster/client.py
`New` commands for clusters and workspace weren't setting the missing name/slug if one was missing.
fixes: #
> refactor(cli): new cluster and workspaces

- silverback/_click_ext.py
- tests/test_cli.py
Tried running `silverback run` in a random directory to see what happens. Got `ModuleNotFounder` error which I thought was kind of strange. I attempted to improve the experience there.
Another try and except and this time raise `click.BadParameter`
Go to a random directory with no bots.
Run `silverback run`
Should see:
```
Usage: silverback run [OPTIONS] [BOT]
Try 'silverback run --help' for help.
Error: Invalid value for '[BOT]': Nothing ro run: No bot argument(s) given and no bots module found.
```
Is much better than it was.
> fix: ModuleNotFound on run cmd

- ape-config.yaml
- silverback/main.py
- silverback/settings.py
This PR adds a settings mode to silverback to trigger every single registered handler (through the default registration interface) using a fork context (e.g. `with ape.networks.fork(): ...`). This potentially unblocks the `BacktestRunner` and `silverback test` by allowing all tests to execute within a fork context off of historical state
depends: https://github.com/ApeWorX/ape/pull/2349
> feat(worker): add SILVERBACK_FORK_MODE handler execution context

- silverback/_cli.py
Looks for the token symbol if the address is valid or if the token symbol is given then it compares it to the accepted tokens list for the network.
fixes: #170
> fix: token flag for cluster pay

- silverback/_cli.py
Add local time zone conversion
fixes: #153
> feat: add local time zone conversion

- silverback/cluster/client.py
Cluster variable endpoints are now `/vars` instead of `/variables`.
fixes: #
> fix: change variable endpoint to vars

- docs/commands/cluster.rst
- docs/userguides/deploying.md
- silverback/_cli.py
Simplified `registry auth` commands to just `registry` to make it easier for users to work with. 
fixes: #
> refactor: simplify registry cli

- silverback/_cli.py
- silverback/cluster/client.py
- silverback/cluster/types.py
> fix(cluster): cluster updates

- silverback/_cli.py
- silverback/cluster/client.py
- silverback/cluster/types.py
> refactor(cluster): make bot logs display better

- silverback/main.py
- silverback/middlewares.py
- silverback/state.py
> fix: pydantic v2 API; incorrect encoding

- silverback/cluster/client.py
Currently, errors in streaming requests (basically just bot logs rn) will raise a different error due to misuse of the httpx API
> fix(cluster): error when handling streaming response exception

- silverback/cluster/types.py
To properly manage resource utilization in the cluster, we need a limit on the number of "guaranteed" concurrent bots, so added that back
This PR also makes significant changes to the `cpu` config item to make it linear (since we have the ability to use arbitrary CPU now), and removes "0" special case options for memory and bandwidth
Lastly, this PR fixes a mistake in labeling bandwidth
> refactor(cluster): add bots back to ClusterConfiguration

- silverback/_cli.py
> fix(cli): don't display VarGroupInfo.id (or .created)

- silverback/cluster/types.py
Forgot to run `.astimezone()` to convert to local time
fixes: #201
> fix(client): render timezone as local time for logs display

- setup.py
- silverback/_cli.py
- silverback/runner.py
Quattro has a Python 3.10+ compatible implementation of TaskGroups (which is 3.11+), and some other nicer API for working with some asyncio functions (such as gather) using TaskGroups where we should get more stable error messages on internal failures (i.e. no leakage of internal tasks failing)
fixes: #67
fixes SBK-428
- Refactored much of the internals of `BaseRunner.run` to use `quattro.gather`
- Override Ape's signal handler to work w/ k8s and `KeyboardInterrupt`
Start the example and `KeyboardInterrupt` at various places during startup/runtime. Also wait long enough for `CircuitBreaker` to naturally trigger shutdown during task exec
> feat(runner): graceful shutdown and SIGINT/SIGTERM handling

- silverback/main.py
I am not sure why, but in some instances I was getting "Invalid container type" for using `ape.contracts.base.ContractEventWrapper`, even though I am not sure how it ended up that way:
```py
...
File "/app/bot.py", line 104, in <module>
@sm.on_stream_funded(bot)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/apepay/manager.py", line 226, in decorator
@app.on_(container)
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/silverback/main.py", line 446, in on_
raise InvalidContainerTypeError(container)
silverback.exceptions.InvalidContainerTypeError: Invalid container type: <class 'ape.contracts.base.ContractEventWrapper'>
```
(From this line: https://github.com/ApeWorX/ApePay/blob/main/sdk/py/apepay/manager.py#L264)
I just handled the issue in …
> fix: allow `ContractEventWrapper` to be used as a task container

- Dockerfile
- setup.py
We no longer use `taskiq-sqs` for cloud use, so build it using the correct plugin
Also updates the base pin for taskiq
> refactor(cluster): update broker plugin for cluster use

- silverback/main.py
Due to a change in the upstream `taskiq` library (released as of 0.11.15), it will attempt to set the value of our system task handler methods `__name__` attribute to another name, which raises an attribute error because methods objects do not allow this
https://github.com/taskiq-python/taskiq/commit/181ff66bee8591a4125d6e2d76604c6dac88058c#diff-f68482a4dddb444455567415d93267303fc5c17b238fd4f2a1e0cc12a654380aR60-R90
Hack for a hack
> fix: taskiq tries to set an illegal attribute of our system task methods

- bots/example.py
- silverback/main.py
Checking "truthiness" of `ape.contracts.base.ContractEvent` object causes it to do `__len__` check to see if `len(event) == 0`, however this causes it to poll every single event log from every single block in a chain's history (obviously insane)
Ape should make an update to these objects to avoid polling entire chain history if a simple `if event` "truthiness" check is done
> fix: accidentally polling logs from entire range of history

- .github/workflows/build.yaml
Noticed that the build for the silverback example bot was hitting a bit of a race condition based on when a release happens
By depending on the build, the example should pick up the latest release as it's base
Check build logs for release
> chore(build): the example image needs the base image

- .github/workflows/build.yaml
Noticed that when we build on release, it wasn't actually pushing the latest example (which therefore isn't pulling in latest stable base image)
> fix(build): also push example image on release

- docs/userguides/development.md
- silverback/exceptions.py
- silverback/main.py
- silverback/state.py
This adds support for tracking and maintaining an internally-tracked nonce inside the `bot` class that supports concurrent use of transaction signing with the signing account
requires: #229
Added `last_nonce_used` to state snapshot feature, and exposed via `bot.nonce`
Needs more real-time testing on a high-speed chain
Note that `bot.nonce` and `bot.signer.nonce` *will track separately* (the later is purely the RPC call to `eth_getNonce`)
> feat: internal nonce tracking via `bot.nonce`

- bots/example.py
- bots/latency-test.py
- silverback/_cli.py
- silverback/main.py
- silverback/middlewares.py
- silverback/runner.py
- silverback/utils.py
- tests/test_utils.py
BREAKING CHANGE(logging): changes the labels of all user tasks
BREAKING CHANGE(platform): runner is not compatible with workers using prev SDK
Major refactor of Silverback's task management system so that it can take advantage of multiprocess workers to reduce latency significantly (in some cases a 20x improvement!)
fixes: #81
1. Moved block/log decoding into the worker side (e.g. `runner.py` -> `main.py`)
2. Put tasks into runner's TaskGroup that exists during runtime
> refactor!: migrate decoding to worker-side, run worker tasks in background

- .github/workflows/build.yaml
Temporarily needed it on a custom tag just to avoid build failure
> chore(CI): revert build action back to v1

- silverback/middlewares.py
Been experimenting with adding new tasks internally to an SDK, and I want to do it in a way where user tasks aren't getting crowded out
> feat(Runner): hide tasks that are configured from an SDK

- silverback/settings.py
Wanted to add out-of-the-box support to the runner for results, but realized it didn't have the in-memory backend to store them by default
> refactor(Results): add default in-memory result backend

- silverback/exceptions.py
- silverback/runner.py
Startup exceptions did not cause an immediate shutdown, due to a recent change in how startup works
fixes: #250 
> fix(runner): handle startup failure correctly

- silverback/runner.py
Don't raise the `NoTasksAvailableError` exception on startup if there is at least 1 cron task
fixes: #243
> fix(Runner): don't raise `NoTasksAvailableError` if a cron tasks exists

- bots/example.py
- docs/userguides/development.md
- silverback/main.py
- silverback/runner.py
- silverback/types.py
This PR adds support for triggering off of metrics generated by other tasks. When a task in silverback executes, it can return a value that will be used to generate a metric that is tracked by the system. This adds additional support for triggering callbacks based on that update to other tasks registered via `bot.on_metrics` (along with additional value-based filters e.g. `>=`, `<`, `!=`) so you can "chain" together tasks to execute based on results generated by other tasks.
fixes: #246 
> feat: metric value triggers

- Dockerfile
- setup.py
- silverback/_cli.py
- silverback/_click_ext.py
Added support for Ory auth system (which happens to work decently well w/ `fief-client` already muhaha)
BREAKING CHANGE: users will have to delete or migrate their `~/.silverback/` folder contents since the the auth tokens are stored there (as well as the auth profile needs to be updated)
> refactor(Cluster): support Ory auth system

- silverback/_click_ext.py
- tests/test_cli.py
Noticed that sometimes there was issues loading a bot when there was other modules in the bot that were not installed properly. Those issues presented under the same error that showed when the bot module itself did not exist. Separated out some of these error conditions, and also added a few more to help users understand how to properly use the `[BOT]` parameter in `silverback run` and `silverback worker` commands, in order to reduce confusion in the CLI.
> fix(CLI): display module errors better
